# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Policies/*

pool:
  vmImage: windows-latest

steps:
  - checkout: self
    fetchDepth: "5"
    clean: "true"

  - task: AzureCLI@2
    displayName: "Pushing Policies to Azure"
    inputs:
      azureSubscription: "judechen-demo-01(d4253ee0-3b4d-4a02-bfe2-71475e7f4a1f)"
      scriptType: "ps"
      scriptLocation: "scriptPath"
      addSpnToEnvironment: true
      scriptPath: "Pipelines/Scripts/armclient.ps1"
