# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Policies/*

pool:
  vmImage: windows-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: "judechen-demo-01(d4253ee0-3b4d-4a02-bfe2-71475e7f4a1f)"
      scriptType: "ps"
      scriptLocation: "inlineScript"
      addSpnToEnvironment: true
      inlineScript: |
        choco install armclient --source=https://chocolatey.org/api/v2/
        ARMClient.exe spn $env:tenantId $env:servicePrincipalId $env:servicePrincipalKey
        #ARMClient.exe get /subscriptions?api-version=2018-01-01
        ## get the changed files
        $files=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
        $filelist=$files -split ' '
        $count=$filelist.Length
        For ($i=0; $i -lt $count; $i++)
        {
          $file=$filelist[$i]
          ## Push policy defitions, assignments, etc.
          Write-Host "Processing file $file"
          if ($file -like "Policies/*/*.json")
          {
            $policy_id=$(Get-Content $file -Raw | ConvertFrom-Json).id
            Write-Host "Processing policy $policy_id"
            ARMClient.exe PUT "$id?api-version=2021-09-01" @$file
          }
        }
